
include(Prebuilt)

if( LINUX )
  if (LL_LINUX_ARM64)
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(GLIB REQUIRED glib-2.0 gio-2.0)
    set(GLIB_FOUND ON CACHE BOOL "Build against glib 2")
    set(GLIB_INCLUDE_DIRS ${GLIB_INCLUDE_DIRS})
    set(GLIB_LIBRARIES ${GLIB_LIBRARIES})
    set(GIO_LIBRARIES ${GLIB_LIBRARIES})
    add_definitions(-DLL_GLIB=1)
    return()
  endif ()
  use_prebuilt_binary(glib)
  set(GLIB_FOUND ON CACHE BOOL "Build against glib 2")
  set(GLIB_INCLUDE_DIRS ${LIBS_PREBUILT_DIR}/include/glib-2.0 ${LIBS_PREBUILT_DIR}/lib/release/glib-2.0/include ) 
  set(GLIB_LIBRARIES libgobject-2.0.a libglib-2.0.a libffi.a libpcre.a)
  set(GIO_LIBRARIES libgio-2.0.a libgmodule-2.0.a -lresolv ${GLIB_LIBRARIES} )
  add_definitions(-DLL_GLIB=1)
endif()
