#!/usr/bin/env python3
"""Generate the obfuscated built-in Tasia GIPHY API key source files.

The input key is read from TASIA_GIPHY_API_KEY. The generated files must not be
committed; they are build artifacts used as a fallback when the runtime viewer
setting is empty.
"""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path


HEADER_GUARD = "LL_TASIA_GIPHY_KEY_GENERATED_H"
SALT_LEN = 16


def mask_byte(seed: int, salt: bytes, index: int) -> int:
    state = (seed + ((index + 1) * 0x9E3779B9)) & 0xFFFFFFFF
    state ^= (state << 13) & 0xFFFFFFFF
    state ^= (state >> 17) & 0xFFFFFFFF
    state ^= (state << 5) & 0xFFFFFFFF
    return ((state & 0xFF) ^ salt[index % len(salt)] ^ ((index * 31) & 0xFF)) & 0xFF


def cpp_array(values: bytes) -> str:
    if not values:
        return "0"

    chunks = []
    for start in range(0, len(values), 12):
        chunk = values[start : start + 12]
        chunks.append("    " + ", ".join(f"0x{value:02x}" for value in chunk))
    return ",\n".join(chunks)


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def generate(header_path: Path, source_path: Path) -> None:
    key = os.environ.get("TASIA_GIPHY_API_KEY", "").strip()
    key_bytes = key.encode("utf-8")

    digest = hashlib.sha256(b"tasia-giphy-key\0" + key_bytes).digest()
    seed = int.from_bytes(digest[:4], "little") or 0x4D4F4D21
    salt = digest[4 : 4 + SALT_LEN] if key_bytes else bytes([0x5A] * SALT_LEN)
    obfuscated = bytes(value ^ mask_byte(seed, salt, index) for index, value in enumerate(key_bytes))

    header = f"""// THIS FILE IS AUTOGENERATED BY scripts/generate_tasia_giphy_key.py
// Do not edit manually. Do not commit this generated file.

#ifndef {HEADER_GUARD}
#define {HEADER_GUARD}

#include <string>

namespace LLTasiaGiphyKeyGenerated
{{
std::string getAPIKey();
bool hasAPIKey();
}}

#endif // {HEADER_GUARD}
"""

    source = f"""// THIS FILE IS AUTOGENERATED BY scripts/generate_tasia_giphy_key.py
// Do not edit manually. Do not commit this generated file.

#include "llviewerprecompiledheaders.h"

#include "lltasia_giphy_key.generated.h"

#include <cstddef>

namespace
{{
static const U32 kSeed = 0x{seed:08x}u;
static const U8 kSalt[] = {{
{cpp_array(salt)}
}};
static const U8 kData[] = {{
{cpp_array(obfuscated)}
}};
static const std::size_t kLength = {len(obfuscated)}u;

U8 maskByte(std::size_t index)
{{
    U32 state = kSeed + static_cast<U32>((index + 1u) * 0x9E3779B9u);
    state ^= state << 13;
    state ^= state >> 17;
    state ^= state << 5;
    return static_cast<U8>((state & 0xffu) ^ kSalt[index % sizeof(kSalt)] ^ ((index * 31u) & 0xffu));
}}
}}

namespace LLTasiaGiphyKeyGenerated
{{
std::string getAPIKey()
{{
    std::string key;
    key.reserve(kLength);
    for (std::size_t index = 0; index < kLength; ++index)
    {{
        key.push_back(static_cast<char>(kData[index] ^ maskByte(index)));
    }}
    return key;
}}

bool hasAPIKey()
{{
    return kLength > 0u;
}}
}}
"""

    write_if_changed(header_path, header)
    write_if_changed(source_path, source)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate obfuscated Tasia GIPHY key source files.")
    parser.add_argument("--header", required=True, type=Path)
    parser.add_argument("--source", required=True, type=Path)
    args = parser.parse_args()

    generate(args.header, args.source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
